-- chatvault schema v6
-- WhatsApp's own on-device message translation (`message.translated_text` in
-- msgstore). Kept alongside the original `messages.text`, never replacing it —
-- the translation is a derived artefact and may be regenerated by the app.
--
-- Filled by the `translations` extractor, which sweeps the full source table on
-- every run (no rowid watermark): a translation is usually requested long after
-- the message arrived, so an incremental pass would miss it forever.

PRAGMA user_version = 6;

ALTER TABLE messages ADD COLUMN translated_text TEXT;

CREATE INDEX IF NOT EXISTS ix_messages_translated
    ON messages(id) WHERE translated_text IS NOT NULL;
